using RealmStudioShapeRenderingLib;

namespace RealmStudioX
{
    public static class RealmTypeUiPolicyFactory
    {
        public static RealmTypeUiPolicy Create(RealmMapType type)
        {
            return type switch
            {
                RealmMapType.World => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = true,
                    ShowLandformTab = true,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = true,
                    ShowLandToolStrip = true,
                    ShowHeightmapMenuEntry = true,
                    ShowHeightMapToolsPanel = true,
                    ShowWorldGlobeMenuEntry = true,
                },

                RealmMapType.Region => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = true,
                    ShowLandformTab = true,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = true,
                    ShowLandToolStrip = true,
                    ShowHeightmapMenuEntry = true,
                    ShowHeightMapToolsPanel = true,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.City => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = true,
                    ShowLandformTab = true,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = true,
                    ShowLandToolStrip = true,
                    ShowHeightmapMenuEntry = true,
                    ShowHeightMapToolsPanel = true,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.Other => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = true,
                    ShowLandformTab = true,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = true,
                    ShowLandToolStrip = true,
                    ShowHeightmapMenuEntry = true,
                    ShowHeightMapToolsPanel = true,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.InteriorFloor => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = false,
                    ShowLandformTab = false,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = true,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = false,
                    ShowLandToolStrip = false,
                    ShowHeightmapMenuEntry = false,
                    ShowHeightMapToolsPanel = false,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.DungeonLevel => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = false,
                    ShowLandformTab = false,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = true,
                    ShowShipTab = false,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = false,
                    ShowLandToolStrip = false,
                    ShowHeightmapMenuEntry = false,
                    ShowHeightMapToolsPanel = false,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.ShipDeck => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = false,
                    ShowLandformTab = false,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = true,
                    ShowPlanetTab = false,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = false,
                    ShowLandToolStrip = false,
                    ShowHeightmapMenuEntry = false,
                    ShowHeightMapToolsPanel = false,
                    ShowWorldGlobeMenuEntry = false,
                },

                RealmMapType.SolarSystemBody => new RealmTypeUiPolicy
                {
                    RealmType = type,
                    ShowBackgroundTab = true,
                    ShowOceanTab = false,
                    ShowLandformTab = false,
                    ShowWaterTab = true,
                    ShowPathsTab = true,
                    ShowSymbolsTab = true,
                    ShowLabelsTab = true,
                    ShowOverlaysTab = true,
                    ShowRegionsTab = true,
                    ShowDrawingTab = true,
                    ShowInteriorTab = false,
                    ShowDungeonTab = false,
                    ShowShipTab = false,
                    ShowPlanetTab = true,
                    ShowBackgroundToolPanel = true,
                    ShowLandToolPanel = false,
                    ShowLandToolStrip = false,
                    ShowHeightmapMenuEntry = false,
                    ShowHeightMapToolsPanel = false,
                    ShowWorldGlobeMenuEntry = false,

                },

                _ => throw new ArgumentException("Unknown or unexpected RealmType")
            };
        }
    }
}
